### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by NicKoehler** [cameronurnes/emby-sync#1]
When I try to log in I get this error:

```
[2020-11-12 22:42:37,781] ERROR in app: Exception on /login [POST]
Traceback (most recent call last):
  File "/home/emby-sync/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/emby-sync/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/emby-sync/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/emby-sync/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/emby-sync/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/emby-sync/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/emby-sync/app/routes.py", line 66, in login
    if not check_password(form.username.data, form.password.data):
  File "/home/emby-sync/app/functions.py", line 30, in check_password
    update_or_create_account(response_json)
  File "/home/emby-sync/app/functions.py", line 37, in update_or_create_account
    user = db.session.query(User).filter_by(username=response['User']['ConnectUserName'].lower()).first()
KeyError: 'ConnectUserName'
192.168.1.254 - - [12/Nov/2020:22:42:37 +0000] "POST /login?next=%2F HTTP/1.1" 500 290 "http://192.168.1.70:5000/login?next=%2F" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4307.0 Safari/537.36 Edg/88.0.692.0"
192.168.1.254 - - [12/Nov/2020:22:42:40 +0000] "GET / HTTP/1.1" 302 237 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4307.0 Safari/537.36 Edg/88.0.692.0"
192.168.1.254 - - [12/Nov/2020:22:42:40 +0000] "GET /login?next=%2F HTTP/1.1" 200 2789 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4307.0 Safari/537.36 Edg/88.0.692.0"
[2020-11-12 22:42:47,496] ERROR in app: Exception on /login [POST]
Traceback (most recent call last):
  File "/home/emby-sync/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/emby-sync/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/emby-sync/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/emby-sync/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/emby-sync/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/emby-sync/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/emby-sync/app/routes.py", line 66, in login
    if not check_password(form.username.data, form.password.data):
  File "/home/emby-sync/app/functions.py", line 30, in check_password
    update_or_create_account(response_json)
  File "/home/emby-sync/app/functions.py", line 37, in update_or_create_account
    user = db.session.query(User).filter_by(username=response['User']['ConnectUserName'].lower()).first()
KeyError: 'ConnectUserName'
```

# Configuration
Operating system:
OS: Pop!_OS 20.10 x86_64
Kernel: 5.8.0-7625-generic
DE: GNOME
WM: Mutter
Docker: 19.03.13, build 4484c46

**Comment by Ninnteen** [comment]
Same here.

**Comment by cameronurnes** [comment]
Looks like the account is not configured with Emby Connect.  At this time, emby connect is required, you cant use just local accounts.

Thanks

**Comment by NicKoehler** [comment]
Another error occours with emby-connect account linked

```
[2020-12-26 20:42:23,142] ERROR in app: Exception on /login [POST]
Traceback (most recent call last):
  File "/home/emby-sync/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/emby-sync/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/emby-sync/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/emby-sync/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/emby-sync/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/emby-sync/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/emby-sync/app/routes.py", line 70, in login
    login_user(user, remember=form.remember_me.data)
  File "/home/emby-sync/venv/lib/python3.7/site-packages/flask_login/utils.py", line 166, in login_user
    if not force and not user.is_active:
AttributeError: 'NoneType' object has no attribute 'is_active'
192.168.1.254 - - [26/Dec/2020:20:42:23 +0000] "POST /login?next=%2F HTTP/1.1" 500 290 "http://192.168.1.70:5000/login?next=%2F" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4346.0 Safari/537.36 Edg/89.0.731.0"
```

**Comment by sebimoe** [comment]
Just to add - I was getting the same issue 

```
ERROR in app: Exception on /login [POST]
...
  File "/home/emby-sync/venv/lib/python3.7/site-packages/flask_login/utils.py", line 166, in login_user
    if not force and not user.is_active:
AttributeError: 'NoneType' object has no attribute 'is_active'
```

It appears to only appear when the local username and linked emby connect usernames are different. Changing local username to match the cloud one makes it go away.

However then I had some weird transient issues with sessions not appearing on the list, and once I added 2 users' sessions (web player) to a room, the initial play was working with about 5 seconds lag however seeking resulted in black screen on followers.

**Comment by cameronurnes** [comment]
Hrm, most of my local usernames are different than the emby connect usernames, will have to dig at that.

**Comment by cameronurnes** [comment]
Work is crazy at the moment though so may be a little while.

**Comment by cameronurnes** [comment]
As far as black screen on followers:  can't help with that, that's on the web player.  All this system does is send commands to the server api, which then sends a seek/pause/play sequence to the player.  Resuming nicely is out of my control unfortunately!

**Comment by Skyfay** [comment]
Will it be possible with local accounts in the future?
That would be extremely cool!

**Comment by Clemens-E** [comment]
I sadly get the same error with an Emby connect account
```
Traceback (most recent call last):
File "/home/emby-sync/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/home/emby-sync/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/emby-sync/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/home/emby-sync/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/home/emby-sync/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/home/emby-sync/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/home/emby-sync/app/routes.py", line 70, in login
login_user(user, remember=form.remember_me.data)
File "/home/emby-sync/venv/lib/python3.7/site-packages/flask_login/utils.py", line 166, in login_user
if not force and not user.is_active:
```
Even after trying an account with the same name as the connected emby account.
is anyone even using this still, or is it deemed broken? Last commit has been a while.

**Comment by Skyfay** [comment]
@Clemens-E I think it's broken :(

**Comment by Clemens-E** [comment]
Bummer, but kind of expected.
I'm now running jellyfin (only for watch parties) with emby and just sync the watched content with some script 😄

**Comment by cameronurnes** [comment]
Should currently work using emby-connect email info, haven't tested other methods.
